CREATE DATABASE TECNOVISION;
USE TECNOVISION;

CREATE TABLE CLIENTE --
(
	ID_CLIENTE BIGINT PRIMARY KEY NOT NULL,
	NOM_CLIENTE VARCHAR(20) NOT NULL,
	APELLIDOS_CLIENTE VARCHAR(20)NOT NULL,
	TEL_CLIENTE BIGINT NOT NULL,
    ESTADO_CLIENTE VARCHAR(20)
);


CREATE TABLE EMPLEADO --
(
	ID_EMPLEADO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_EMPLEADO CHAR (30)NOT NULL,
	DIRECCION_EMPLEADO CHAR (45)NOT NULL,
	TEL_EMPLEADO BIGINT NOT NULL,
	SALARIO_EMPLEADO FLOAT NOT NULL,
	FECHA_INGRESO_EMPLEADO DATETIME NOT NULL,
    ID_CARGO_EMPLEADO_FK BIGINT,
    ID_USUARIO_EMPLEADO_FK BIGINT
);



SELECT * FROM USUARIO;


CREATE TABLE USUARIO
(
	ID_USUARIO BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(40) NOT NULL,
    CONTRA_USUARIO VARCHAR(40) NOT NULL
);

INSERT INTO USUARIO VALUES (1, 'Usuario1', '123');


Select * from USUARIO;

CREATE TABLE PAGOS --
(
	ID_PAGO BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	VALOR_PAGO FLOAT NOT NULL,
    ID_CLIENTE_PAGO_FK BIGINT,
    ID_FACTURA_PAGO_FK BIGINT
);

CREATE TABLE PRODUCTOS --
(
	ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_PRODUCTO CHAR(20) NOT NULL,
	CANT_PRODUCTO BIGINT NOT NULL,
	PRECIO_PRODUCTO FLOAT NOT NULL,
	FECHA_PRODUCTO DATETIME NOT NULL
);




CREATE TABLE FRA_VENTA --
(
	ID_FRA_VENTA BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SALDO_FRA_VENTA FLOAT NOT NULL,
	ABONO_FRA_VENTA FLOAT NOT NULL,
	IVA_FRA_VENTA FLOAT NOT NULL,
	FECHA_FRA_VENTA DATETIME NOT NULL,
	VALOR_FRA_VENTA FLOAT NOT NULL,
    ID_CLIENTE_FRA_VENTA_FK BIGINT,
    ID_EMPLEADO_FRA_VENTA_FK BIGINT,
    ID_FORMA_PAGO_FRA_VENTA BIGINT
);

SELECT * FROM FRA_VENTA;

CREATE TABLE DETALLE_VENTA --
(
	CANT_DETALLE_VENTA BIGINT NOT NULL,
	SUBTOTAL_DETALLE_VENTA BIGINT NOT NULL,
	VALOR_UNIDAD_DETALLE_VENTA BIGINT NOT NULL,
    ID_PRODUCTO_DETALLE_VENTA_FK BIGINT NULL,
    ID_FRA_VENTA_FK BIGINT NULL,
    FOREIGN KEY (ID_PRODUCTO_DETALLE_VENTA_FK) REFERENCES PRODUCTOS (ID_PRODUCTO),
    FOREIGN KEY (ID_FRA_VENTA_FK) REFERENCES FRA_VENTA (ID_FRA_VENTA)
);


CREATE TABLE FORMA_PAGO --
(
	ID_FORMA_PAGO BIGINT PRIMARY KEY NOT NULL,
	NOM_FORMA_PAGO VARCHAR(20) NOT NULL
);

CREATE TABLE CARGO --
(
	ID_CARGO BIGINT PRIMARY KEY NOT NULL,
	NOM_CARGO VARCHAR(20) NOT NULL
);

INSERT INTO CARGO VALUES (6, 'Pruebas 1');

UPDATE CARGO SET NOM_CARGO = 'Pruebas 2' WHERE ID_CARGO = 6;

DELETE FROM CARGO WHERE ID_CARGO = 6;

SELECT * FROM CARGO;


CREATE TABLE PROVEEDOR --
(
	ID_PROVEEDOR BIGINT PRIMARY KEY NOT NULL,
	NOM_PROVEEDOR VARCHAR(20) NOT NULL,
	TEL_PROVEEDOR BIGINT NOT NULL,
	DIRECCION_PROVEEDOR VARCHAR (45) NOT NULL
);

INSERT INTO PROVEEDOR VALUES (1, 'RayBan', 5462859, 'Cll 80');


CREATE TABLE FRA_COMPRA --
(
	ID_FRA_COMPRA BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SALDO_FRA_COMPRA FLOAT NOT NULL,
	ABONO_FRA_COMPRA FLOAT NOT NULL,
	IVA_FRA_COMPRA FLOAT NOT NULL,
	FECHA_FRA_COMPRA DATETIME NOT NULL,
	VALOR_FRA_COMPRA FLOAT NOT NULL,
    ID_EMPLEADO_FRA_COMPRA_FK BIGINT,
    ID_PROVEEDOR_FRA_COMPRA_FK BIGINT
);

SELECT * FROM FRA_VENTA;

CREATE TABLE DETALLE_COMPRA --
(
	CANT_DETALLE_COMPRA BIGINT NOT NULL,
	SUBTOTAL_DETALLE_COMPRA BIGINT NOT NULL,
	VALOR_UNIDAD_DETALLE_COMPRA BIGINT NOT NULL,
    ID_PRODUCTO_DETALLE_COMPRA_FK BIGINT,
    ID_FRA_COMPRA_FK BIGINT
);



INSERT INTO DETALLE_VENTA VALUES (1, 1, 1, 1, 1);
