USE TECNOVISION;

DELIMITER $$
CREATE PROCEDURE CONSULTAGE_CLIENTE()
BEGIN
SELECT ID_CLIENTE, NOM_CLIENTE, TEL_CLIENTE
FROM CLIENTE;
END $$
CALL CONSULTAGE_CLIENTE;

DELIMITER $$
CREATE PROCEDURE CONSULTAGE_EMPLEADO()
BEGIN
SELECT ID_EMPLEADO, NOMBRE_EMPLEADO, TEL_EMPLEADO, SALARIO_EMPLEADO, FECHA_INGRESO_EMPLEADO, ID_CARGO_EMPLEADO_FK
FROM EMPLEADO;
END $$
CALL CONSULTAGE_EMPLEADO;


DELIMITER $$
CREATE PROCEDURE CONSULTAGE_PAGO()
BEGIN
SELECT VALOR_PAGO, ID_CLIENTE_PAGO_FK 
FROM PAGOS;
END $$
CALL CONSULTAGE_PAGO;


DELIMITER $$
CREATE PROCEDURE CONSULTAGE_PRODUCTO()
BEGIN
SELECT ID_PRODUCTO, NOMBRE_PRODUCTO, CANT_PRODUCTO, PRECIO_PRODUCTO 
FROM PRODUCTOS;
END $$
CALL CONSULTAGE_PRODUCTO;



DELIMITER $$
CREATE PROCEDURE CONSULTAGE_FRA_VENTA()
BEGIN
SELECT ID_FRA_VENTA, SALDO_FRA_VENTA, ABONO_FRA_VENTA, IVA_FRA_VENTA, FECHA_FRA_VENTA, VALOR_FRA_VENTA, ID_CLIENTE_FRA_VENTA_FK
FROM FRA_VENTA;
END $$
CALL CONSULTAGE_FRA_VENTA;



DELIMITER $$
CREATE PROCEDURE CONSULTAGE_DETALLE_VENTA()
BEGIN
SELECT ID_FRA_VENTA_FK, ID_PRODUCTO_DETALLE_VENTA_FK, VALOR_UNIDAD_DETALLE_VENTA
FROM DETALLE_VENTA;
END $$
CALL CONSULTAGE_DETALLE_VENTA;

DELIMITER $$
CREATE PROCEDURE CONSULTAGE_FORMA_PAGO()
BEGIN
SELECT ID_FORMA_PAGO, NOM_FORMA_PAGO
FROM FORMA_PAGO;
END $$
CALL CONSULTAGE_FORMA_PAGO;


DELIMITER $$
CREATE PROCEDURE CONSULTAGE_CARGO()
BEGIN
SELECT ID_CARGO, NOM_CARGO
FROM CARGO;
END $$
CALL CONSULTAGE_CARGO;


DELIMITER $$
CREATE PROCEDURE CONSULTAGE_PROVEEDOR()
BEGIN
SELECT ID_PROVEEDOR, NOM_PROVEEDOR, TEL_PROVEEDOR
FROM PROVEEDOR;
END $$
CALL CONSULTAGE_PROVEEDOR;

DELIMITER $$
CREATE PROCEDURE CONSULTAGE_FRA_COMPRA()
BEGIN
SELECT ID_FRA_COMPRA, SALDO_FRA_COMPRA, ABONO_FRA_COMPRA, FECHA_FRA_COMPRA, VALOR_FRA_COMPRA, ID_EMPLEADO_FRA_COMPRA_FK
FROM FRA_COMPRA;
END $$
CALL CONSULTAGE_FRA_COMPRA;


DELIMITER $$
CREATE PROCEDURE CONSULTAGE_DETALLE_COMPRA()
BEGIN
SELECT ID_FRA_COMPRA_FK, SUBTOTAL_DETALLE_COMPRA, VALOR_UNIDAD_DETALLE_COMPRA, CANT_DETALLE_COMPRA
FROM DETALLE_COMPRA;
END $$
CALL CONSULTAGE_DETALLE_COMPRA;


































