USE TECNOVISION;

-- CLIENTE --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_CLIENTE
(
	IN _ID_CLIENTE BIGINT
)
BEGIN
	SELECT ID_CLIENTE AS ID, NOM_CLIENTE AS NOMBRE, APELLIDOS_CLIENTE AS APELLIDOS, TEL_CLIENTE AS TELEFONO
    FROM CLIENTE
    WHERE ID_CLIENTE = _ID_CLIENTE;
END $$

CALL CONSULTAR_CLIENTE (1);

-- EMPLEADO --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_EMPLEADO
(
	IN _ID_EMPLEADO BIGINT
)
BEGIN
	SELECT ID_EMPLEADO AS ID, NOMBRE_EMPLEADO AS NOMBRE, DIRECCION_EMPLEADO AS DIRECCION, TEL_EMPLEADO AS TELEFONO, SALARIO_EMPLEADO AS SALARIO, FECHA_INGRESO_EMPLEADO AS FECHA_DE_INGRESO, ID_CARGO_EMPLEADO_FK AS CARGO
    FROM EMPLEADO
    WHERE ID_EMPLEADO = _ID_EMPLEADO;
END $$

CALL CONSULTAR_EMPLEADO (1);

-- PAGO --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_PAGO
(
	IN _ID_PAGO BIGINT
)
BEGIN
	SELECT VALOR_PAGO AS VALOR,  ID_CLIENTE_PAGO_FK AS ID_CLIENTE
    FROM PAGOS
    WHERE ID_PAGO = _ID_PAGO;
END $$

CALL CONSULTAR_PAGO (1);

-- PRODUCTOS --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_PRODUCTO
(
	IN _ID_PRODUCTO BIGINT
)
BEGIN
	SELECT ID_PRODUCTO AS ID, NOMBRE_PRODUCTO AS NOMBRE, CANT_PRODUCTO AS CANTIDAD, PRECIO_PRODUCTO AS PRECIO, FECHA_PRODUCTO AS FECHA
    FROM PRODUCTO
    WHERE ID_PRODUCTO = _ID_PRODUCTO;
END $$

CALL CONSULTAR_PRODUCTO (1);

-- FRA_VENTA --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_FRA_VENTA
(
	IN _ID_FRA_VENTA BIGINT
)
BEGIN
	SELECT ID_FRA_VENTA AS ID, SALDO_FRA_VENTA AS SALDO, ABONO_FRA_VENTA AS ABONO, IVA_FRA_VENTA AS IVA, FECHA_FRA_VENTA AS FECHA, VALOR_FRA_VENTA AS VALOR, ID_CLIENTE_FRA_VENTA_FK AS ID_CLIENTE, ID_EMPLEADO_FRA_VENTA_FK, ID_FORMA_PAGO_FRA_VENTA AS ID_FORMA_DE_PAGO
    FROM FRA_VENTA
    WHERE ID_FRA_VENTA = _ID_FRA_VENTA;
END $$

CALL CONSULTAR_FRA_VENTA (1);

-- DETALLE_VENTA --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_DETALLE_VENTA
(
	IN _CANT_DETALLE_VENTA BIGINT
)
BEGIN
	SELECT CANT_DETALLE_VENTA AS CANT, SUBTOTAL_DETALLE_VENTA AS SUBTOTAL, VALOR_UNIDAD_DETALLE_VENTA AS VALOR_UNITARIO, ID_PRODUCTO_DETALLE_VENTA_FK AS ID_PRODUCTO, ID_FRA_VENTA_FK AS ID_FACTURA
    FROM DETALLE_VENTA
    WHERE CANT_DETALLE_VENTA = _CANT_DETALLE_VENTA;
END $$

CALL CONSULTAR_DETALLE_VENTA (1);

-- FORMA_PAGO --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_FORMA_PAGO
(
	IN _ID_FORMA_PAGO BIGINT
)
BEGIN
	SELECT ID_FORMA_PAGO AS ID, NOM_FORMA_PAGO AS NOMBRE
    FROM FORMA_PAGO
    WHERE ID_FORMA_PAGO = _ID_FORMA_PAGO;
END $$

CALL CONSULTAR_FORMA_PAGO (1);

-- CARGO --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_CARGO
(
	IN _ID_CARGO BIGINT
)
BEGIN
	SELECT ID_CARGO AS ID, NOM_CARGO AS NOMBRE
    FROM FORMA_PAGO
    WHERE ID_CARGO = _ID_CARGO;
END $$

CALL CONSULTAR_CARGO (1);

-- PROVEEDOR --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_PROVEEDOR
(
	IN _ID_PROVEEDOR BIGINT
)
BEGIN
	SELECT ID_PROVEEDOR AS ID, NOM_PROVEEDOR AS NOMBRE, TEL_PROVEEDOR AS TELEFONO, DIRECCION_PROVEEDOR AS DIRECCION
    FROM PROVEEDOR
    WHERE ID_PROVEEDOR = _ID_PROVEEDOR;
END $$

CALL CONSULTAR_PROVEEDOR (1);

-- FRA_COMPRA --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_FRA_COMPRA
(
	IN _ID_FRA_COMPRA BIGINT
)
BEGIN
	SELECT ID_FRA_COMPRA AS ID, SALDO_FRA_COMPRA AS SALDO, ABONO_FRA_COMPRA AS ABONO, IVA_FRA_COMPRA AS IVA, FECHA_FRA_COMPRA AS FECHA, VALOR_FRA_COMPRA AS VALOR, ID_EMPLEADO_FRA_COMPRA_FK AS ID_EMPLEADO, ID_PROVEEDOR_FRA_COMPRA_FK AS ID_PROVEEDOR
    FROM FRA_COMPRA
    WHERE ID_FRA_COMPRA = _ID_FRA_COMPRA;
END $$

CALL CONSULTAR_FRA_COMPRA (1);

-- DETALLE_COMPRA --

DELIMITER $$
CREATE PROCEDURE CONSULTAR_DETALLE_COMPRA
(
	IN _CANT_DETALLE_COMPRA BIGINT
)
BEGIN
	SELECT CANT_DETALLE_COMPRA AS CANTIDAD, SUBTOTAL_DETALLE_COMPRA AS SUBTOTAL, VALOR_UNIDAD_DETALLE_COMPRA AS VALOR, ID_PRODUCTO_DETALLE_COMPRA_FK AS ID_PRODUCTO, ID_FRA_COMPRA_FK AS ID_FACTURA
    FROM DETALLE_COMPRA
    WHERE CANT_DETALLE_COMPRA = _CANT_DETALLE_COMPRA;
END $$

CALL CONSULTAR_DETALLE_COMPRA (1);