USE TECNOVISION;
ALTER TABLE PAGOS ADD FOREIGN KEY (ID_CLIENTE_PAGO_FK) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE PAGOS ADD FOREIGN KEY (ID_FACTURA_PAGO_FK) REFERENCES FRA_VENTA (ID_FRA_VENTA);

ALTER TABLE FRA_COMPRA ADD FOREIGN KEY (ID_EMPLEADO_FRA_COMPRA_FK) REFERENCES EMPLEADO (ID_EMPLEADO);--
ALTER TABLE FRA_COMPRA ADD FOREIGN KEY (ID_PROVEEDOR_FRA_COMPRA_FK) REFERENCES PROVEEDOR (ID_PROVEEDOR);--

ALTER TABLE DETALLE_COMPRA ADD FOREIGN KEY (ID_PRODUCTO_DETALLE_COMPRA_FK) REFERENCES PRODUCTOS(ID_PRODUCTO);--
ALTER TABLE DETALLE_COMPRA ADD FOREIGN KEY (ID_FRA_COMPRA_FK) REFERENCES FRA_COMPRA(ID_FRA_COMPRA);--

ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_CARGO_EMPLEADO_FK) REFERENCES CARGO(ID_CARGO);--
ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_USUARIO_EMPLEADO_FK) REFERENCES USUARIO(ID_USUARIO);--

ALTER TABLE FRA_VENTA ADD FOREIGN KEY (ID_CLIENTE_FRA_VENTA_FK) REFERENCES CLIENTE (ID_CLIENTE);--
ALTER TABLE FRA_VENTA ADD FOREIGN KEY (ID_EMPLEADO_FRA_VENTA_FK) REFERENCES EMPLEADO (ID_EMPLEADO);--
ALTER TABLE FRA_VENTA ADD FOREIGN KEY (ID_FORMA_PAGO_FRA_VENTA) REFERENCES FORMA_PAGO (ID_FORMA_PAGO);--

ALTER TABLE DETALLE_VENTA ADD FOREIGN KEY (ID_PRODUCTO_DETALLE_VENTA_FK) REFERENCES PRODUCTOS(ID_PRODUCTO);--
ALTER TABLE DETALLE_VENTA ADD FOREIGN KEY (ID_FRA_VENTA_FK) REFERENCES FRA_VENTA(ID_FRA_VENTA);


