USE TECNOVISION;

-- INSERTAR CLIENTE --

DELIMITER $$
CREATE PROCEDURE INSERTAR_CLIENTE
(
	IN _ID_CLIENTE BIGINT ,
	IN _NOM_CLIENTE VARCHAR(20),
	IN _APELLIDOS_CLIENTE VARCHAR(20),
	IN _TEL_CLIENTE BIGINT
)
BEGIN 
	INSERT INTO CLIENTE VALUES (_ID_CLIENTE, _NOM_CLIENTE, _APELLIDOS_CLIENTE, _TEL_CLIENTE);
END $$

-- INSERTAR EMPLEADO --

DELIMITER $$
CREATE PROCEDURE INSERTAR_EMPLEADO
(
	IN _ID_EMPLEADO BIGINT,
	IN _NOMBRE_EMPLEADO CHAR (30),
	IN _DIRECCION_EMPLEADO CHAR (45),
	IN _TEL_EMPLEADO BIGINT,
	IN _SALARIO_EMPLEADO FLOAT,
	IN _FECHA_INGRESO_EMPLEADO DATETIME,
    IN _ID_CARGO_EMPLEADO_FK BIGINT,
    IN _ID_USUARIO_EMPLEADO_FK BIGINT
)
BEGIN 
	INSERT INTO EMPLEADO VALUES (_ID_EMPLEADO, _NOMBRE_EMPLEADO, _DIRECCION_EMPLEADO, _TEL_EMPLEADO, _SALARIO_EMPLEADO, _FECHA_INGRESO_EMPLEADO, _ID_CARGO_EMPLEADO_FK, _ID_USUARIO_EMPLEADO_FK);
END $$

-- INSERTAR USUARIO --

DELIMITER $$
CREATE PROCEDURE INSERTAR_USUARIO
(
	IN _ID_USUARIO BIGINT,
	IN _NOMBRE_USUARIO VARCHAR (40),
	IN _CONTRASEÑA_EMPLEADO VARCHAR (40)
)
BEGIN 
	INSERT INTO USUARIO VALUES (_ID_USUARIO, _NOMBRE_USUARIO, _CONTRASEÑA_USUARIO);
END $$

-- INSERTAR PAGOS --

DELIMITER $$
CREATE PROCEDURE INSERTAR_PAGOS
(
	IN _VALOR_PAGO FLOAT,
    IN _ID_CLIENTE_PAGO_FK BIGINT
)
BEGIN 
	INSERT INTO PAGOS VALUES (_VALOR_PAGO, _ID_CLIENTE_PAGO_FK);
END $$

-- INSERTAR PRODUCTOS --

DELIMITER $$
CREATE PROCEDURE INSERTAR_PRODUCTOS
(
	IN _ID_PRODUCTO BIGINT ,
	IN _NOMBRE_PRODUCTO CHAR(20),
	IN _CANT_PRODUCTO BIGINT,
	IN _PRECIO_PRODUCTO FLOAT,
	IN _FECHA_PRODUCTO DATETIME
)
BEGIN 
	INSERT INTO PRODUCTOS VALUES (_ID_PRODUCTO, _NOMBRE_PRODUCTO, _CANT_PRODUCTO, _PRECIO_PRODUCTO, _FECHA_PRODUCTO);
END $$

-- INSERTAR FRA_VENTA --

DELIMITER $$
CREATE PROCEDURE INSERTAR_FRA_VENTA
(
	IN _ID_FRA_VENTA BIGINT,
	IN _SALDO_FRA_VENTA FLOAT,
	IN _ABONO_FRA_VENTA FLOAT,
	IN _IVA_FRA_VENTA FLOAT,
	IN _FECHA_FRA_VENTA DATETIME,
	IN _VALOR_FRA_VENTA FLOAT,
    IN _ID_CLIENTE_FRA_VENTA_FK BIGINT,
    IN _ID_EMPLEADO_FRA_VENTA_FK BIGINT,
    IN _ID_FORMA_PAGO_FRA_VENTA BIGINT
)
BEGIN 
	INSERT INTO FRA_VENTA VALUES (_ID_FRA_VENTA, _SALDO_FRA_VENTA, _ABONO_FRA_VENTA, _IVA_FRA_VENTA, _FECHA_FRA_VENTA, _VALOR_FRA_VENTA, _ID_CLIENTE_FRA_VENTA_FK, _ID_EMPLEADO_FRA_VENTA_FK, _ID_FORMA_PAGO_FRA_VENTA);
END $$

-- INSERTAR DETALLE_VENTA --

DELIMITER $$
CREATE PROCEDURE INSERTAR_DETALLE_VENTA
(
	IN _CANT_DETALLE_VENTA BIGINT,
	IN _SUBTOTAL_DETALLE_VENTA BIGINT,
	IN _VALOR_UNIDAD_DETALLE_VENTA BIGINT,
    IN _ID_PRODUCTO_DETALLE_VENTA_FK BIGINT,
    IN _ID_FRA_VENTA_FK BIGINT
)
BEGIN 
	INSERT INTO DETALLE_VENTA VALUES (_CANT_DETALLE_VENTA, _SUBTOTAL_DETALLE_VENTA, _VALOR_UNIDAD_DETALLE_VENTA, _ID_PRODUCTO_DETALLE_VENTA_FK, _ID_FRA_VENTA_FK);
END $$

-- INSERTAR FORMA_PAGO --

DELIMITER $$
CREATE PROCEDURE INSERTAR_FORMA_PAGO
(
	IN _ID_FORMA_PAGO BIGINT,
	IN _NOM_FORMA_PAGO VARCHAR(20)
)
BEGIN 
	INSERT INTO FORMA_PAGO VALUES (_ID_FORMA_PAGO, _NOM_FORMA_PAGO);
END $$

-- INSERTAR CARGO --

DELIMITER $$
CREATE PROCEDURE INSERTAR_CARGO
(
	IN _ID_CARGO BIGINT,
	IN _NOM_CARGO VARCHAR(20)
)
BEGIN 
	INSERT INTO CARGO VALUES (_ID_CARGO, _NOM_CARGO);
END $$

-- INSERTAR PROVEEDOR --

DELIMITER $$
CREATE PROCEDURE INSERTAR_PROVEEDOR
(
	IN _ID_PROVEEDOR BIGINT,
	IN _NOM_PROVEEDOR VARCHAR(20),
	IN _TEL_PROVEEDOR BIGINT,
	IN _DIRECCION_PROVEEDOR VARCHAR (45)
)
BEGIN 
	INSERT INTO PROVEEDOR VALUES (_ID_PROVEEDOR, _NOM_PROVEEDOR, _TEL_PROVEEDOR, _DIRECCION_PROVEEDOR);
END $$

-- INSERTAR FRA_COMPRA --

DELIMITER $$
CREATE PROCEDURE INSERTAR_FRA_COMPRA
(
	IN _ID_FRA_COMPRA BIGINT,
	IN _SALDO_FRA_COMPRA FLOAT,
	IN _ABONO_FRA_COMPRA FLOAT,
	IN _IVA_FRA_COMPRA FLOAT,
	IN _FECHA_FRA_COMPRA DATETIME,
	IN _VALOR_FRA_COMPRA FLOAT,
    IN _ID_EMPLEADO_FRA_COMPRA_FK BIGINT,
    IN _ID_PROVEEDOR_FRA_COMPRA_FK BIGINT
)
BEGIN 
	INSERT INTO FRA_COMPRA VALUES (_ID_FRA_COMPRA, _SALDO_FRA_COMPRA, _ABONO_FRA_COMPRA, _IVA_FRA_COMPRA, _FECHA_FRA_COMPRA, _VALOR_FRA_COMPRA, _ID_EMPLEADO_FRA_COMPRA_FK, _ID_PROVEEDOR_FRA_COMPRA_FK);
END $$

-- INSERTAR DETALLE_COMPRA --

DELIMITER $$
CREATE PROCEDURE INSERTAR_DETALLE_COMPRA
(
	IN _CANT_DETALLE_COMPRA BIGINT,
	IN _SUBTOTAL_DETALLE_COMPRA BIGINT,
	IN _VALOR_UNIDAD_DETALLE_COMPRA BIGINT,
    IN _ID_PRODUCTO_DETALLE_COMPRA_FK BIGINT,
    IN _ID_FRA_COMPRA_FK BIGINT
)
BEGIN 
	INSERT INTO DETALLE_COMPRA VALUES (_CANT_DETALLE_COMPRA, _SUBTOTAL_DETALLE_COMPRA, _VALOR_UNIDAD_DETALLE_COMPRA, _ID_PRODUCTO_DETALLE_COMPRA_FK, _ID_FRA_COMPRA_FK);
END $$


