USE TECNOVISION;
DELIMITER $$
CREATE PROCEDURE UPDATE_CARGO
(
	IN _ID_CARGO BIGINT,
    IN _NOM_CARGO VARCHAR (20)
)
BEGIN
UPDATE CARGO SET ID_CARGO = _ID_CARGO,  NOM_CARGO = _NOM_CARGO WHERE ID_CARGO = _ID_CARGO;
END$$

CALL UPDATE_CARGO (1, 'SECRETARIO');

DELIMITER $$
CREATE PROCEDURE UPDATE_CLIENTE
(
	IN _ID_CLIENTE BIGINT,
    IN _NOM_CLIENTE VARCHAR (20),
    IN _APELLIDOS_CLIENTE VARCHAR(20),
    IN _TEL_CLIENTE BIGINT
)
BEGIN
UPDATE CLIENTE SET ID_CLIENTE = _ID_CLIENTE,  NOM_CLIENTE = _NOM_CLIENTE, APELLIDOS_CLIENTE = _APELLIDOS_CLIENTE, TEL_CLIENTE = _TEL_CLIENTE WHERE ID_CLIENTE = _ID_CLIENTE;
END$$
CALL UPDATE_CLIENTE (5, 'JUANA', 'MOLANO', 4523075);
SELECT * FROM CLIENTE;
DELIMITER $$
CREATE PROCEDURE UPDATE_DETALLE_COMPRA
(
	IN _CANT_DETALLE_COMPRA BIGINT,
    IN _SUBTOTAL_DETALLE_COMPRA BIGINT,
    IN _VALOR_UNIDAD_DETALLE_COMPRA BIGINT,
    IN _ID_PRODUCTO_DETALLE_COMPRA_FK BIGINT,
    IN _ID_FRA_COMPRA_FK BIGINT
)
BEGIN
UPDATE DETALLE_COMPRA SET CANT_DETALLE_COMPRA = _CANT_DETALLE_COMPRA,  SUBTOTAL_DETALLE_COMPRA = _SUBTOTAL_DETALLE_COMPRA, VALOR_UNIDAD_DETALLE_COMPRA = _VALOR_UNIDAD_DETALLE_COMPRA, ID_PRODUCTO_DETALLE_COMPRA_FK = _ID_PRODUCTO_DETALLE_COMPRA_FK, ID_FRA_COMPRA_FK = _ID_FRA_COMPRA_FK WHERE CANT_DETALLE_COMPRA = _CANT_DETALLE_COMPRA;
END$$
CALL UPDATE_DETALLE_COMPRA (2, 25000, 20000, 1, 2);

DELIMITER $$
CREATE PROCEDURE UPDATE_DETALLE_VENTA
(
	IN _CANT_DETALLE_VENTA BIGINT,
    IN _SUBTOTAL_DETALLE_VENTA BIGINT,
    IN _VALOR_UNIDAD_DETALLE_VENTA BIGINT,
    IN _ID_PRODUCTO_DETALLE_VENTA_FK BIGINT,
    IN _ID_FRA_VENTA_FK BIGINT
)
BEGIN
UPDATE DETALLE_VENTA SET CANT_DETALLE_VENTA = _CANT_DETALLE_VENTA,  SUBTOTAL_DETALLE_VENTA = _SUBTOTAL_DETALLE_VENTA, VALOR_UNIDAD_DETALLE_VENTA = _VALOR_UNIDAD_DETALLE_VENTA, ID_PRODUCTO_DETALLE_VENTA_FK = _ID_PRODUCTO_DETALLE_VENTA_FK, ID_FRA_VENTA_FK = _ID_FRA_VENTA_FK WHERE CANT_DETALLE_VENTA = _CANT_DETALLE_VENTA;
END$$
CALL UPDATE_DETALLE_VENTA (4, 8541000, 10000, 2, 1);
SELECT * FROM DETALLE_VENTA;
DELIMITER $$
CREATE PROCEDURE UPDATE_EMPLEADO
(
	IN _ID_EMPLEADO BIGINT,
    IN _NOMBRE_EMPLEADO CHAR (30),
    IN _DIRECCION_EMPLEADO CHAR(45),
    IN _TEL_EMPLEADO BIGINT,
    IN _SALARIO_EMPLEADO FLOAT,
    IN _FECHA_INGRESO_EMPLEADO DATETIME,
    IN _ID_CARGO_EMPLEADO_FK BIGINT
)
BEGIN
UPDATE EMPLEADO SET ID_EMPLEADO = _ID_EMPLEADO,  NOMBRE_EMPLEADO = _NOMBRE_EMPLEADO, DIRECCION_EMPLEADO = _DIRECCION_EMPLEADO, TEL_EMPLEADO = _TEL_EMPLEADO, SALARIO_EMPLEADO = _SALARIO_EMPLEADO, FECHA_INGRESO_EMPLEADO = _FECHA_INGRESO_EMPLEADO, ID_CARGO_EMPLEADO_FK = _ID_CARGO_EMPLEADO_FK WHERE ID_EMPLEADO = _ID_EMPLEADO;
END$$
CALL UPDATE_EMPLEADO (4, 'MARTÍN', 'CLL 35 SUR #69C 33', 4682415, 5000000, '2016/10/13', 1);

DELIMITER $$
CREATE PROCEDURE UPDATE_FORMA_PAGO
(
	IN _ID_FORMA_PAGO BIGINT,
    IN _NOM_FORMA_PAGO CHAR (20)
)
BEGIN
UPDATE FORMA_PAGO SET ID_FORMA_PAGO = _ID_FORMA_PAGO,  NOM_FORMA_PAGO = _NOM_FORMA_PAGO WHERE ID_FORMA_PAGO = _ID_FORMA_PAGO;
END$$
CALL UPDATE_FORMA_PAGO (5, 'CREDITO');

DELIMITER $$
CREATE PROCEDURE UPDATE_FRA_COMPRA
(
	IN _ID_FRA_COMPRA BIGINT,
    IN _SALDO_FRA_COMPRA FLOAT,
    IN _ABONO_FRA_COMPRA FLOAT,
    IN _IVA_FRA_COMPRA FLOAT,
    IN _FECHA_FRA_COMPRA DATETIME,
    IN _VALOR_FRA_COMPRA FLOAT,
    IN _ID_EMPLEADO_FRA_COMPRA_FK BIGINT,
    IN _ID_PROVEEDOR_FRA_COMPRA_FK BIGINT
)
BEGIN
UPDATE FRA_COMPRA SET ID_FRA_COMPRA = _ID_FRA_COMPRA,  SALDO_FRA_COMPRA = _SALDO_FRA_COMPRA, ABONO_FRA_COMPRA = _ABONO_FRA_COMPRA, IVA_FRA_COMPRA = _IVA_FRA_COMPRA, FECHA_FRA_COMPRA = _FECHA_FRA_COMPRA, VALOR_FRA_COMPRA = _VALOR_FRA_COMPRA, ID_EMPLEADO_FRA_COMPRA_FK = _ID_EMPLEADO_FRA_COMPRA_FK, ID_PROVEEDOR_FRA_COMPRA_FK = _ID_PROVEEDOR_FRA_COMPRA_FK WHERE ID_FRA_COMPRA = _ID_FRA_COMPRA;
END$$
CALL UPDATE_FRA_COMPRA(3, 20000, 100000, 1100, '2019/05/27', 120000, 5, 4);

DELIMITER $$
CREATE PROCEDURE UPDATE_FRA_VENTA
(
	IN _ID_FRA_VENTA BIGINT,
    IN _SALDO_FRA_VENTA FLOAT,
    IN _ABONO_FRA_VENTA FLOAT,
    IN _IVA_FRA_VENTA FLOAT,
    IN _FECHA_FRA_VENTA DATETIME,
    IN _VALOR_FRA_VENTA FLOAT,
    IN _ID_CLIENTE_FRA_VENTA_FK BIGINT,
    IN _ID_EMPLEADO_FRA_VENTA_FK BIGINT,
    IN _ID_FORMA_PAGO_FRA_VENTA BIGINT
)
BEGIN
UPDATE FRA_VENTA SET ID_FRA_VENTA = _ID_FRA_VENTA,  SALDO_FRA_VENTA = _SALDO_FRA_VENTA, ABONO_FRA_VENTA = _ABONO_FRA_VENTA, IVA_FRA_VENTA = _IVA_FRA_VENTA, FECHA_FRA_VENTA = _FECHA_FRA_VENTA, VALOR_FRA_VENTA = _VALOR_FRA_VENTA, ID_CLIENTE_FRA_VENTA_FK = _ID_CLIENTE_FRA_VENTA_FK, ID_EMPLEADO_FRA_VENTA_FK = _ID_EMPLEADO_FRA_VENTA_FK, ID_FORMA_PAGO_FRA_VENTA = _ID_FORMA_PAGO_FRA_VENTA WHERE ID_FRA_VENTA = _ID_FRA_VENTA;
END$$
CALL UPDATE_FRA_COMPRA(2, 10000, 20000, 1100, '2019/03/21', 30000, 1, 5);

DELIMITER $$
CREATE PROCEDURE UPDATE_PAGOS
(
	IN _VALOR_PAGO FLOAT,
    IN _ID_CLIENTE_PAGO_FK BIGINT
)
BEGIN
UPDATE PAGOS SET VALOR_PAGO = _VALOR_PAGO,  ID_CLIENTE_PAGO_FK = _ID_CLIENTE_PAGO_FK WHERE VALOR_PAGO = _VALOR_PAGO;
END$$
CALL UPDATE_PAGOS (50000, 1);

DELIMITER $$
CREATE PROCEDURE UPDATE_PRODUCTO
(
	IN _ID_PRODUCTO BIGINT,
    IN _NOMBRE_PRODUCTO CHAR(20),
    IN _CANT_PRODUCTO BIGINT,
    IN _PRECIO_PRODUCTO FLOAT,
    IN _FECHA_PRODUCTO DATETIME
)
BEGIN
UPDATE PRODUCTOS SET ID_PRODUCTO = _ID_PRODUCTO,  NOMBRE_PRODUCTO = _NOMBRE_PRODUCTO, CANT_PRODUCTO = _CANT_PRODUCTO, PRECIO_PRODUCTO = _PRECIO_PRODUCTO, FECHA_PRODUCTO = _FECHA_PRODUCTO WHERE ID_PRODUCTO = _ID_PRODUCTO;
END$$
CALL UPDATE_PRODUCTO(3, 'LENTES MIRAFLEX', 110, 33000, '2019/08/01');

DELIMITER $$
CREATE PROCEDURE UPDATE_PROVEEDOR
(
	IN _ID_PROVEEDOR BIGINT,
    IN _NOM_PROVEEDOR VARCHAR(20),
    IN _TEL_PROVEEDOR BIGINT,
    IN _DIRECCION_PROVEEDOR VARCHAR(45)
)
BEGIN
UPDATE PROVEEDOR SET ID_PROVEEDOR = _ID_PROVEEDOR,  NOM_PROVEEDOR = _NOM_PROVEEDOR, TEL_PROVEEDOR = _TEL_PROVEEDOR, DIRECCION_PROVEEDOR = _DIRECCION_PROVEEDOR WHERE ID_PROVEEDOR = _ID_PROVEEDOR;
END$$
CALL UPDATE_PROVEEDOR (3, 'SMART EYES', 3163904,'AV 40 #57C 22');























